### PR TITLE
Move audit structure back to team 2

### PR DESCRIPTION
**Pull request by arnavk1006**
Since no other team seems to be using the global audit structure, moved it back to reduce clutter.

### CODE REVIEW

**Review by aaashah — APPROVED** [review]

**Review by nlewxxs — CHANGES_REQUESTED** [review]
Hi, we are about to use it!!!

- team 1 and 4

**Comment by nlewxxs** [comment]
can we have 15m to look at the code pls? Might still be okay. @dhruvds12

**Comment by arnavxkohli** [comment]
Ah ok then, if you don't end up using it lmk. But until then I won't merge this.

**Comment by dhruvds12** [comment]
@arnavxkohli Team 1 is now using this global audit structure! I think this PR can be closed.

**Pull request closed without merging**
