### PR TITLE
update team5AoA

### PR DESCRIPTION
**Pull request by sodabreak**

### CODE REVIEW

**Review by vedantvasugupta — APPROVED** [review]
LGTM

**Review by kisaagatuna — APPROVED** [review]

**Comment by kishan-v** [comment]
Wait guys please can we allow a bit more time for reviewing and merging PRs that modify `EnvironmentServer` and other people's AoA code. @sodabreak @kisaagatuna @vedantvasugupta

**Comment by johanjino** [comment]
Hmm excuse me ??? You cant change run turn for each AoA?? It has to been same for everyone??

**Comment by kishan-v** [comment]
Any AoA specific logic you want to run in `RunTurn()` should be included in AoA functions like the following:
`AoA.RunPostContributionAoaLogic()`

**Comment by sodabreak** [comment]
> Hi Are we allowed to change run turn for each AoA?? It has to be same for everyone right??

I'm sorry for that, we have to make some small changes to our run turn, so if a team is using aoa5 will go on runturteam5, others will remain as defult.

**Comment by kishan-v** [comment]
> > Hi Are we allowed to change run turn for each AoA?? It has to be same for everyone right??
> 
> I'm sorry for that, we have to make some small changes to our run turn, so if a team is using aoa5 will go on runturteam5, others will remain as defult.

Are you able to implement it like [this](https://github.com/ADimoska/SOMASExtended/pull/112#issuecomment-2518114553)?
@sodabreak

**Comment by sodabreak** [comment]
> Any AoA specific logic you want to run in `RunTurn()` should be included in AoA functions like the following: `AoA.RunPostContributionAoaLogic()`

I tried to include that in `AoA.RunPostContributionAoaLogic()`, but it may cause re-include of  EnvironmentServer，which is unacceptable, any good suggestions? we want to get each agent's score

**Pull request merged**
