### PR TITLE
quick update team6 aoas

### PR DESCRIPTION
**Pull request by roryabrooks**

### CODE REVIEW

**Review by johanjino — CHANGES_REQUESTED** [review]
unapprove

There is no changes here? Is this a mistake?

**Review by dhruvds12 — CHANGES_REQUESTED** [review]
There's no functional changes here, is that intentional?

**Comment by roryabrooks** [comment]
> There's no functional changes here, is that intentional?

Yeah sry I realised the change that I did fucked the  logic a little so tried to roll it back bc I thought pull req had already been approved whoops

**Comment by dhruvds12** [comment]
Ok, I'll close this PR then

**Pull request closed without merging**
