### PR TITLE
No Time to Die

### PR DESCRIPTION
**Pull request by johanjino**
Commenting out the test for now, cause no time to fix it. And main works... So far.....

### CODE REVIEW

**Comment by johanjino** [comment]
James Bond throws gun

**Comment by kishan-v** [comment]
Approved

**Review by kishan-v — APPROVED** [review]

**Review by dhruvds12 — APPROVED** [review]

**Review by dhruvds12 — CHANGES_REQUESTED** [review]
@nlewxxs to fix

**Comment by johanjino** [comment]
Indiana Jones shoots swordsman

**Review by dhruvds12 — DISMISSED** [review]

**Comment by nlewxxs** [comment]
## Team 4 Please check
- the `TestCondorcetWinner` test is only failing when we try and call `Team1_AgreeRankBoundaries` on any **team 4 agent**
- This works perfectly for base agents, team1, team2 and team3 agents. 
- I have temporarily removed team4 agents from being created in the `CreateTestServer` function.

I suspect this is as a result of you using the `MI_256` agent, it's not implementing everything from ExtendedAgent. I had this problem earlier when I was trying to monkeypatch the function for your agents. 

It's strange that we're not encountering this when running main. 

Any ideas? @Somewheref @EXiao3

**Comment by dhruvds12** [comment]
@nlewxxs @Somewheref  @EXiao3 Can this be actioned, I have code that needs to be merged waiting on this

**Comment by nlewxxs** [comment]
All good now, basically no changes had to be made. Some modifications to `RemoveAgent` at some point broke the test, not the MI_256 as I incorrectly suspected.

**Review by dhruvds12 — APPROVED** [review]

**Review by nlewxxs — APPROVED** [review]

**Pull request merged**
