### PR TITLE
Agent Names

### PR DESCRIPTION
**Pull request by ADimoska**
Created a function called GetName that can be used instead of GetID in Logs/Prints for readability. 
The names are given to the agents at the server entry by order. The first agent that enters the server is called 1, the second is called 2...
I am happy to update the logs/prints with this function on Thursday morning if this pull request gets approved

### CODE REVIEW

**Comment by kishan-v** [comment]
@kushk2 a had some thoughts about this issue

**Comment by kushk2** [comment]
yeah this is a clean solution - nice work

**Review by kishan-v — COMMENTED** [review]
One alternative is just adding `.String()[:4]` in every log statement that includes an agent UUID. This will print the first 2 bytes (4 hex chars) which is shorter than the full ID, and still guaranteed to be unique (65,535 possibilities).

```go
log.Printf("Agent %s is withdrawing %d from the common pool of size %d\n", mi.GetID().String()[:4], withdrawal, commonPool)
```

If we wanted to go down this route of adding human friendly names to the agents (e.g. Team 1 Agent A), I think we could set a name field in the constructor - no need to have a getter and setter function. We would pass the name in the Line 67 `for` loop.

**Review by johanjino — APPROVED** [review]
LGTM

**Review by kushk2 — APPROVED** [review]

**Pull request merged**
