### PR TITLE
Kill agent was causing the Segmentation Error Fault

### PR DESCRIPTION
**Pull request by vedantvasugupta**
Related to issue #52 

This PR resolves an issue where the KillAgent function causes a panic when attempting to remove an agent that is not part of any team (teamID == uuid.Nil).

Changes Made:
Updated KillAgent to handle agents without a team by:
Always removing the agent from the agent map.
Adding the agent to the deadAgents list.
Ensuring proper checks for nil and non-existent agents.

### CODE REVIEW

**Comment by arnavxkohli** [comment]
@vedantvasugupta LGMT, made sure there were no conflicts with the current main branch

**Review by arnavxkohli — APPROVED** [review]

**Comment by nlewxxs** [comment]
Most of the stuff in the diff is the same as #65 or am I wrong?

**Review by nlewxxs — APPROVED** [review]
Will need to do another branch to merge orphan leaving and joining together.

**Comment by nlewxxs** [comment]
what's going on here?

**Comment by johanjino** [comment]
Will mark this stale, and close PR if it does not get fixed

**Comment by dhruvds12** [comment]
@vedantvasugupta closing this pr

**Pull request closed without merging**
