### PR TITLE
Allow Orphans to Rejoin Teams at the start of a turn (no messages)

### PR DESCRIPTION
**Pull request by nlewxxs**
### Process Outline
- At the start of each `RunTurn()`, we call two new functions:
- `PickUpOrphans()` - the server iterates over the agent map and identifies any agents with a `nil` TeamID. It updates the common pool with the preferences of that agent - (the agent is free to modify its preferences at any point, we expose a Getter to the server so that it can update its records.)
- `AllocateOrphans()` - the server goes through each orphan's preferences and, for each team, calls a vote whether that agent should be accepted or not. If the vote is above a certain threshold (currently 70%, should this be defined in the AoA?), then the agent is accepted.  

In order to trigger re-allocation then, all an agent needs to do is set it's TeamID to `nil` and update it's preferences. The server will automatically pick it up at the start of the next `RunTurn()` call. 

### Tests: 
- `TestAlwaysAccept` - Agents always accept the orphans
- `TestAlwaysReject` - Agents always reject the orphans
- `TestAcceptIfInCurrentTeam` - An example strategy where an agent votes 'yes' to accept an orphan that is already in its team. This won't actually happen, it's just an example of some simple logic. 
- `TestAllocateOrphans` - Creates a team with 2 members, and leaves 2 orphans unallocated. Assigns the preferences of the orphans, and the server allocates them by calling a vote.

### CODE REVIEW

**Comment by kishan-v** [comment]
LGTM! Glad we have our original orphan pool logic back.
The unit tests are much appreciated @nlewxxs

**Review by kishan-v — APPROVED** [review]

**Review by johanjino — APPROVED** [review]
Trusting @kishan-v .
Approving this 😂😭

**Comment by kishan-v** [comment]
> Trusting @kishan-v . Approving this 😂😭

Oh god, nothing good ever follows those words 😬 
I've put my faith in the unit tests.

**Comment by nlewxxs** [comment]
Will need some tweaking to work properly in-game, I'll probably have to sit down with @vedantvasugupta to get it working with his leaving logic.

**Pull request merged**
