### PR TITLE
fix: ensure overriden function is called when called indirectly in another function

### PR DESCRIPTION
**Pull request by kishan-v**
Merge @harryknee 's pull request https://github.com/ADimoska/SOMASExtended/pull/42 into main

-----

_Fix for issue #36_

_Current implementation is adding additional param for all functions **calling** overridable functions. Signature for overridable functions do not require any change, only when it is called (should only impact the infra team)._

### CODE REVIEW

**Review by dhruvds12 — APPROVED** [review]
LGTM!

**Comment by ajanthan-k** [comment]
How about this instead?:

```go
func (mi *ExtendedAgent) GetSelf() common.IExtendedAgent {
    return mi.BaseAgent.AccessAgentByID(mi.GetID())
}
```

```go
func (mi *ExtendedAgent) StartRollingDice() {
    agent := mi.GetSelf()
    ...
        willStick = agent.StickOrAgain()
    ...
```

Seems to work when I try it with overridden `StickOrAgain`.

**Review by johanjino — APPROVED** [review]
LGTM

**Comment by dhruvds12** [comment]
@harryknee if you are happy to merge this, go ahead.

**Pull request merged**
